Server:
  Env: test
  Port: 3000

JWT:
  SigningKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  TokenExpiration: 24

Database:
  Host: localhost
  Port: 3306
  Username: root
  Password:
  DBName: gorengan_testing
